apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  labels:
    app: demo
spec:
  containers:
  - name: broken-app
    image: nonexistent-image:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
